### ISSUE TITLE
Unity character model: project su-a

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/ARCounseling#15]
https://youtu.be/pliUFrpciCQ

기사를 좀 찾아보니 전문 3D 캐릭터 디자이너가 몇 달에 걸쳐 만든 작품이라고 합니다.

**Comment by bungabear** [comment]
저도 예전에 기사로 얼핏 본적은 있던거 같네요.
전 회사에서 버츄얼유투버 지아 영상을 데모용으로 쓴적이 있었는데, 지아도 만든 분이신가봐요.
[Article](http://blog.naver.com/PostView.nhn?blogId=unity_kr&logNo=221909853462&redirect=Dlog&widgetTypeCall=true&directAccess=false) [Twitter](https://twitter.com/rumiga0)
