### ISSUE TITLE
Development device: macbook pro 13

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/ARCounseling#5]
5년이 넘지 않는 한도내에 맥북 모델을 중고로 구매하는게 낫다고 판단

2015년 이후 맥북프로 13인치, 메모리 8G, 128G 저장장치라도
50만원 이하 구매 가능하다면 구매하여 개발 빌드용으로 사용.

중고나라 검색 시작...

**Comment by jongfeel** [comment]
의외로 cpu 세대 차이에 따라 성능 차이가 있어서
고민 끝에 최신 맥북프로 2019년형 중 가장 싼 중고 제품을 노리고 있는 중

맥북프로 2019년 13인치 SSD 128G CTO
세제품: 153만원대
중고: 120~125만원대

**Comment by jongfeel** [comment]
맥북프로 2019년 13인치 SSD 128G
120만에 중고로 구매 결정

**Comment by jongfeel** [comment]
맥북도 결국 구매 완료!

**Comment by bungabear** [comment]
저도 학교 아이맥 원격으로는 안되겠어서
2019 맥북프로 13 기본형 중고구매하러 합니다~~
