### ISSUE TITLE
ARKit face tracking demo run

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/ARCounseling#6]
macbook pro xCode build, install to iPad mini

**Comment by jongfeel** [comment]
CAN'T NOT SUPPORT iPad mini 5 gen.
Because, iPad mini has not true depth camera.
Face tracking working only recent device with true depth camera

https://docs.unity3d.com/Packages/com.unity.xr.arkit-face-tracking@4.0/manual/index.html

**Comment by Ellago0918** [comment]
안녕하세요~

**Comment by bungabear** [comment]
closed를 잘못해서 먼저 눌렀네요;;  
지난 회의에서 보여드렸던대로  
[AR BlendShape example in ARFoundation](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/FaceTracking/ARKitFaceBlendShapes.unity)  
iPhone X에서 동작 확인 하였습니다.  
스크린샷은 퇴근후에 붙이도록 할께요

**Comment by jongfeel** [comment]
Confirmed #13 online meeting demo
