### ISSUE TITLE
WebRTC demo run test on macbook and iPad mini

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/ARCounseling#7]
webrtc communication test on macbook and ipad

audio and video communication establish perfect!

![image](https://user-images.githubusercontent.com/17442457/80785784-6a321100-8bbc-11ea-98cb-47e325d62b84.png)

![image](https://user-images.githubusercontent.com/17442457/80785764-5d152200-8bbc-11ea-9533-e342d1c93c66.png)

**Comment by bungabear** [comment]
[ARFoundation BlendShape ](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scenes/FaceTracking/ARKitFaceBlendShapes.unity) 예제와 [VideoInput의 VirtualCamera](https://github.com/jongfeel/ARCounseling/blob/master/Assets/WebRtcVideoChat/extra/VideoInput/videoInput.unity)를 이용하여 
macbook unity와 iPhone X의 AR 카메라 영상 통화 동작 확인하였습니다.
퇴근 후 스크린샷 및 코드 첨부하도록 하겠습니다.

**Comment by jongfeel** [comment]
@bungabear 

다른 issue를 생성해서 공유해 주시면 좋을 거 같습니다.

이 이슈는 종료할께요.
